{
  typeLabel: {
    name: 'feature-request'
  },
  candidateMilestone: {
    number: 2,
    name: 'Backlog Candidates'
  },
  approvedMilestone: {
    number: 1,
    name: 'Backlog'
  },
  onLabeled: {
    delay: 5,
    perform: true
  },
  onCandidateMilestoned: {
    candidatesComment: 'Your feature request is now a backlog candidate.',
    perform: true
  },
  onMonitorUpvotes: {
    upvoteThreshold: 1,
    acceptedComment: 'Your feature request gather sufficient upvotes and has been moved to the backlog.',
    perform: false
  },
  onMonitorDaysOnCandidateMilestone: {
    daysOnMilestone: 0,
    declinedComment: 'In the last 60 days your feature request did not gather sufficient interest from the community.',
    perform: false
  }
}