{
  typeLabel: {
    name: 'feature-request'
  },
  candidateMilestone: {
    number: 2,
    name: 'Backlog Candidates'
  },
  approvedMilestone: {
    number: 1,
    name: 'Backlog'
  },
  onLabeled: {
    delay: 5,
    perform: true
  },
  onCandidateMilestoned: {
    candidatesComment: 'This feature request is now a backlog candidate. Read more about the life-cycle of feature requests [here](https://aka.ms/vscode-issue-lifecycle).',
    perform: true
  },
  onMonitorUpvotes: {
    upvoteThreshold: 1,
    acceptanceComment: 'This feature request gathered a sufficient number of upvotes and is now on the backlog. Read more about the life-cycle of feature requests [here](https://aka.ms/vscode-issue-lifecycle).',
    perform: true
  },
  onMonitorDaysOnCandidateMilestone: {
    daysOnMilestone: 0,
    rejectionComment: 'This feature request has not gathered a sufficient number of upvotes and is now closed. Read more about the life-cycle of feature requests [here](https://aka.ms/vscode-issue-lifecycle).',
    perform: false
  }
}