pool:
  vmImage: "ubuntu-latest"

trigger: none

resources:
  pipelines:
  - pipeline: testissuesBuild
    source: testissues-build
    trigger: 
      branches:
        include:
          - 'main'
          - 'release/*'

steps:
- script: |
    echo HERE2
