name: CI

on:
  push:
    branches:
      - '**'

jobs:
  here:
    name: HERE
    runs-on: windows-latest
    steps:
      - run: "& 'C:\\Program Files\\Docker\\Docker\\DockerCli.exe' -h"
      - run: "& 'C:\\Program Files\\Docker\\Docker\\DockerCli.exe' -SwitchLinuxEngine"
      - run: docker info
